# syntax=docker/dockerfile:1
# Lightweight Dockerfile: use pre-built nvcr.io/nvidian/nemo-rl:nightly and only add NeMo-Skills.
# To use the image without building at all, set containers.nemo-rl to nvcr.io/nvidian/nemo-rl:nightly
# in your cluster config (see cluster_configs/example-local.yaml).

ARG NEMO_RL_IMAGE=nvcr.io/nvidian/nemo-rl:nightly

FROM ${NEMO_RL_IMAGE}

USER root
